# Generated by Django 3.1a1 on 2020-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piza_topping', models.CharField(choices=[('Ch', 'Cheese'), ('TO', 'Tomato'), ('ON', 'Onion'), ('CO', 'Corn'), ('CA', 'Capcicum')], max_length=2)),
                ('piza_shape', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large')], max_length=10)),
                ('piza_size', models.CharField(choices=[('R', 'Regular'), ('S', 'Square')], max_length=1)),
            ],
        ),
    ]
